/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ue_O1_measurements.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ue_O1_measurements.pb-c.h"
void   o1_measurements_report__init
                     (O1MeasurementsReport         *message)
{
  static O1MeasurementsReport init_value = O1_MEASUREMENTS_REPORT__INIT;
  *message = init_value;
}
size_t o1_measurements_report__get_packed_size
                     (const O1MeasurementsReport *message)
{
  assert(message->base.descriptor == &o1_measurements_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t o1_measurements_report__pack
                     (const O1MeasurementsReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &o1_measurements_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t o1_measurements_report__pack_to_buffer
                     (const O1MeasurementsReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &o1_measurements_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
O1MeasurementsReport *
       o1_measurements_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (O1MeasurementsReport *)
     protobuf_c_message_unpack (&o1_measurements_report__descriptor,
                                allocator, len, data);
}
void   o1_measurements_report__free_unpacked
                     (O1MeasurementsReport *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &o1_measurements_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor o1_measurements_report__field_descriptors[8] =
{
  {
    "imsi",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(O1MeasurementsReport, imsi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_power_avg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_rx_power_avg),
    offsetof(O1MeasurementsReport, rx_power_avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_power_tot",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_rx_power_tot),
    offsetof(O1MeasurementsReport, rx_power_tot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n0_power_avg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_n0_power_avg),
    offsetof(O1MeasurementsReport, n0_power_avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n0_power_tot",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_n0_power_tot),
    offsetof(O1MeasurementsReport, n0_power_tot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_rssi_dBm",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_rx_rssi_dbm),
    offsetof(O1MeasurementsReport, rx_rssi_dbm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssb_rsrp_dBm",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_ssb_rsrp_dbm),
    offsetof(O1MeasurementsReport, ssb_rsrp_dbm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mcs",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(O1MeasurementsReport, has_mcs),
    offsetof(O1MeasurementsReport, mcs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned o1_measurements_report__field_indices_by_name[] = {
  0,   /* field[0] = imsi */
  7,   /* field[7] = mcs */
  3,   /* field[3] = n0_power_avg */
  4,   /* field[4] = n0_power_tot */
  1,   /* field[1] = rx_power_avg */
  2,   /* field[2] = rx_power_tot */
  5,   /* field[5] = rx_rssi_dBm */
  6,   /* field[6] = ssb_rsrp_dBm */
};
static const ProtobufCIntRange o1_measurements_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor o1_measurements_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "O1MeasurementsReport",
  "O1MeasurementsReport",
  "O1MeasurementsReport",
  "",
  sizeof(O1MeasurementsReport),
  8,
  o1_measurements_report__field_descriptors,
  o1_measurements_report__field_indices_by_name,
  1,  o1_measurements_report__number_ranges,
  (ProtobufCMessageInit) o1_measurements_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
