/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: O1_measurements.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "O1_measurements.pb-c.h"
void   o1_measurement_report__init
                     (O1MeasurementReport         *message)
{
  static const O1MeasurementReport init_value = O1_MEASUREMENT_REPORT__INIT;
  *message = init_value;
}
size_t o1_measurement_report__get_packed_size
                     (const O1MeasurementReport *message)
{
  assert(message->base.descriptor == &o1_measurement_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t o1_measurement_report__pack
                     (const O1MeasurementReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &o1_measurement_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t o1_measurement_report__pack_to_buffer
                     (const O1MeasurementReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &o1_measurement_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
O1MeasurementReport *
       o1_measurement_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (O1MeasurementReport *)
     protobuf_c_message_unpack (&o1_measurement_report__descriptor,
                                allocator, len, data);
}
void   o1_measurement_report__free_unpacked
                     (O1MeasurementReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &o1_measurement_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   o1_uemeasurement_report__init
                     (O1UEMeasurementReport         *message)
{
  static const O1UEMeasurementReport init_value = O1_UEMEASUREMENT_REPORT__INIT;
  *message = init_value;
}
size_t o1_uemeasurement_report__get_packed_size
                     (const O1UEMeasurementReport *message)
{
  assert(message->base.descriptor == &o1_uemeasurement_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t o1_uemeasurement_report__pack
                     (const O1UEMeasurementReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &o1_uemeasurement_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t o1_uemeasurement_report__pack_to_buffer
                     (const O1UEMeasurementReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &o1_uemeasurement_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
O1UEMeasurementReport *
       o1_uemeasurement_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (O1UEMeasurementReport *)
     protobuf_c_message_unpack (&o1_uemeasurement_report__descriptor,
                                allocator, len, data);
}
void   o1_uemeasurement_report__free_unpacked
                     (O1UEMeasurementReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &o1_uemeasurement_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   o1_gnbmeasurement_report__init
                     (O1GNBMeasurementReport         *message)
{
  static const O1GNBMeasurementReport init_value = O1_GNBMEASUREMENT_REPORT__INIT;
  *message = init_value;
}
size_t o1_gnbmeasurement_report__get_packed_size
                     (const O1GNBMeasurementReport *message)
{
  assert(message->base.descriptor == &o1_gnbmeasurement_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t o1_gnbmeasurement_report__pack
                     (const O1GNBMeasurementReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &o1_gnbmeasurement_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t o1_gnbmeasurement_report__pack_to_buffer
                     (const O1GNBMeasurementReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &o1_gnbmeasurement_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
O1GNBMeasurementReport *
       o1_gnbmeasurement_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (O1GNBMeasurementReport *)
     protobuf_c_message_unpack (&o1_gnbmeasurement_report__descriptor,
                                allocator, len, data);
}
void   o1_gnbmeasurement_report__free_unpacked
                     (O1GNBMeasurementReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &o1_gnbmeasurement_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   o1_ulschfailure__init
                     (O1ULSCHFailure         *message)
{
  static const O1ULSCHFailure init_value = O1_ULSCHFAILURE__INIT;
  *message = init_value;
}
size_t o1_ulschfailure__get_packed_size
                     (const O1ULSCHFailure *message)
{
  assert(message->base.descriptor == &o1_ulschfailure__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t o1_ulschfailure__pack
                     (const O1ULSCHFailure *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &o1_ulschfailure__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t o1_ulschfailure__pack_to_buffer
                     (const O1ULSCHFailure *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &o1_ulschfailure__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
O1ULSCHFailure *
       o1_ulschfailure__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (O1ULSCHFailure *)
     protobuf_c_message_unpack (&o1_ulschfailure__descriptor,
                                allocator, len, data);
}
void   o1_ulschfailure__free_unpacked
                     (O1ULSCHFailure *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &o1_ulschfailure__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   o1_rrcfailure__init
                     (O1RRCFailure         *message)
{
  static const O1RRCFailure init_value = O1_RRCFAILURE__INIT;
  *message = init_value;
}
size_t o1_rrcfailure__get_packed_size
                     (const O1RRCFailure *message)
{
  assert(message->base.descriptor == &o1_rrcfailure__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t o1_rrcfailure__pack
                     (const O1RRCFailure *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &o1_rrcfailure__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t o1_rrcfailure__pack_to_buffer
                     (const O1RRCFailure *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &o1_rrcfailure__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
O1RRCFailure *
       o1_rrcfailure__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (O1RRCFailure *)
     protobuf_c_message_unpack (&o1_rrcfailure__descriptor,
                                allocator, len, data);
}
void   o1_rrcfailure__free_unpacked
                     (O1RRCFailure *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &o1_rrcfailure__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor o1_measurement_report__field_descriptors[4] =
{
  {
    "ue_msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(O1MeasurementReport, ue_msg),
    &o1_uemeasurement_report__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gnb_msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(O1MeasurementReport, gnb_msg),
    &o1_gnbmeasurement_report__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ulf",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(O1MeasurementReport, ulf),
    &o1_ulschfailure__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrcf",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(O1MeasurementReport, rrcf),
    &o1_rrcfailure__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned o1_measurement_report__field_indices_by_name[] = {
  1,   /* field[1] = gnb_msg */
  3,   /* field[3] = rrcf */
  0,   /* field[0] = ue_msg */
  2,   /* field[2] = ulf */
};
static const ProtobufCIntRange o1_measurement_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor o1_measurement_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "O1MeasurementReport",
  "O1MeasurementReport",
  "O1MeasurementReport",
  "",
  sizeof(O1MeasurementReport),
  4,
  o1_measurement_report__field_descriptors,
  o1_measurement_report__field_indices_by_name,
  1,  o1_measurement_report__number_ranges,
  (ProtobufCMessageInit) o1_measurement_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor o1_uemeasurement_report__field_descriptors[9] =
{
  {
    "imsi",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, imsi),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_power_avg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, rx_power_avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_power_tot",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, rx_power_tot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n0_power_avg",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, n0_power_avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n0_power_tot",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, n0_power_tot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_rssi_dBm",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, rx_rssi_dbm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssb_rsrp_dBm",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, ssb_rsrp_dbm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mcs",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, mcs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rnti",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1UEMeasurementReport, rnti),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned o1_uemeasurement_report__field_indices_by_name[] = {
  0,   /* field[0] = imsi */
  7,   /* field[7] = mcs */
  3,   /* field[3] = n0_power_avg */
  4,   /* field[4] = n0_power_tot */
  8,   /* field[8] = rnti */
  1,   /* field[1] = rx_power_avg */
  2,   /* field[2] = rx_power_tot */
  5,   /* field[5] = rx_rssi_dBm */
  6,   /* field[6] = ssb_rsrp_dBm */
};
static const ProtobufCIntRange o1_uemeasurement_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor o1_uemeasurement_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "O1UEMeasurementReport",
  "O1UEMeasurementReport",
  "O1UEMeasurementReport",
  "",
  sizeof(O1UEMeasurementReport),
  9,
  o1_uemeasurement_report__field_descriptors,
  o1_uemeasurement_report__field_indices_by_name,
  1,  o1_uemeasurement_report__number_ranges,
  (ProtobufCMessageInit) o1_uemeasurement_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor o1_gnbmeasurement_report__field_descriptors[8] =
{
  {
    "rnti",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, rnti),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avg_rsrp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, avg_rsrp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srs_wide_band_snr",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, srs_wide_band_snr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dlsch_mcs",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, dlsch_mcs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ulsch_mcs",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, ulsch_mcs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cqi",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, cqi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dlsch_bler",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, dlsch_bler),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ulsch_bler",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(O1GNBMeasurementReport, ulsch_bler),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned o1_gnbmeasurement_report__field_indices_by_name[] = {
  1,   /* field[1] = avg_rsrp */
  5,   /* field[5] = cqi */
  6,   /* field[6] = dlsch_bler */
  3,   /* field[3] = dlsch_mcs */
  0,   /* field[0] = rnti */
  2,   /* field[2] = srs_wide_band_snr */
  7,   /* field[7] = ulsch_bler */
  4,   /* field[4] = ulsch_mcs */
};
static const ProtobufCIntRange o1_gnbmeasurement_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor o1_gnbmeasurement_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "O1GNBMeasurementReport",
  "O1GNBMeasurementReport",
  "O1GNBMeasurementReport",
  "",
  sizeof(O1GNBMeasurementReport),
  8,
  o1_gnbmeasurement_report__field_descriptors,
  o1_gnbmeasurement_report__field_indices_by_name,
  1,  o1_gnbmeasurement_report__number_ranges,
  (ProtobufCMessageInit) o1_gnbmeasurement_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor o1_ulschfailure__field_descriptors[2] =
{
  {
    "rnti",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1ULSCHFailure, rnti),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failure",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1ULSCHFailure, failure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned o1_ulschfailure__field_indices_by_name[] = {
  1,   /* field[1] = failure */
  0,   /* field[0] = rnti */
};
static const ProtobufCIntRange o1_ulschfailure__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor o1_ulschfailure__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "O1ULSCHFailure",
  "O1ULSCHFailure",
  "O1ULSCHFailure",
  "",
  sizeof(O1ULSCHFailure),
  2,
  o1_ulschfailure__field_descriptors,
  o1_ulschfailure__field_indices_by_name,
  1,  o1_ulschfailure__number_ranges,
  (ProtobufCMessageInit) o1_ulschfailure__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor o1_rrcfailure__field_descriptors[2] =
{
  {
    "rnti",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1RRCFailure, rnti),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failure",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(O1RRCFailure, failure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned o1_rrcfailure__field_indices_by_name[] = {
  1,   /* field[1] = failure */
  0,   /* field[0] = rnti */
};
static const ProtobufCIntRange o1_rrcfailure__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor o1_rrcfailure__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "O1RRCFailure",
  "O1RRCFailure",
  "O1RRCFailure",
  "",
  sizeof(O1RRCFailure),
  2,
  o1_rrcfailure__field_descriptors,
  o1_rrcfailure__field_indices_by_name,
  1,  o1_rrcfailure__number_ranges,
  (ProtobufCMessageInit) o1_rrcfailure__init,
  NULL,NULL,NULL    /* reserved[123] */
};
