# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ue_O1_measurements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ue_O1_measurements.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18ue_O1_measurements.proto\"\xb4\x01\n\x14O1MeasurementsReport\x12\x0c\n\x04imsi\x18\x01 \x01(\t\x12\x14\n\x0crx_power_avg\x18\x02 \x01(\x05\x12\x14\n\x0crx_power_tot\x18\x03 \x01(\x05\x12\x14\n\x0cn0_power_avg\x18\x04 \x01(\x05\x12\x14\n\x0cn0_power_tot\x18\x05 \x01(\x05\x12\x13\n\x0brx_rssi_dBm\x18\x06 \x01(\x05\x12\x14\n\x0cssb_rsrp_dBm\x18\x07 \x01(\x05\x12\x0b\n\x03mcs\x18\x08 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_O1MEASUREMENTSREPORT = _descriptor.Descriptor(
  name='O1MeasurementsReport',
  full_name='O1MeasurementsReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imsi', full_name='O1MeasurementsReport.imsi', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_power_avg', full_name='O1MeasurementsReport.rx_power_avg', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_power_tot', full_name='O1MeasurementsReport.rx_power_tot', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n0_power_avg', full_name='O1MeasurementsReport.n0_power_avg', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n0_power_tot', full_name='O1MeasurementsReport.n0_power_tot', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_rssi_dBm', full_name='O1MeasurementsReport.rx_rssi_dBm', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssb_rsrp_dBm', full_name='O1MeasurementsReport.ssb_rsrp_dBm', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mcs', full_name='O1MeasurementsReport.mcs', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=209,
)

DESCRIPTOR.message_types_by_name['O1MeasurementsReport'] = _O1MEASUREMENTSREPORT

O1MeasurementsReport = _reflection.GeneratedProtocolMessageType('O1MeasurementsReport', (_message.Message,), dict(
  DESCRIPTOR = _O1MEASUREMENTSREPORT,
  __module__ = 'ue_O1_measurements_pb2'
  # @@protoc_insertion_point(class_scope:O1MeasurementsReport)
  ))
_sym_db.RegisterMessage(O1MeasurementsReport)


# @@protoc_insertion_point(module_scope)
